name: Notify Webhook

on:
  push:
    branches:
      - staging

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook notification
        run: |
          curl -X POST http://localhost:3040/webhook -H "Content-Type: application/json" -d '{"message": "GitHub Action triggered on staging branch"}'
