name: Notify Webhook

on:
  push:
    branches:
      - staging

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send full GitHub Actions payload to webhook
        run: |
          curl -X POST http://localhost:3040/webhook \
            -H "Content-Type: application/json" \
            --data-binary @"$GITHUB_EVENT_PATH"

